import React,{useState}from'react';import{createRoot}from'react-dom/client';import{api,PaymentMethod}from'./api';import'./pos.css';
type Item={id:string;barcode:string;name:string;qty:number;price:number;stock:number};
const STORE=import.meta.env.VITE_STORE_ID??'';const WAREHOUSE=import.meta.env.VITE_WAREHOUSE_ID??'';const REGISTER=import.meta.env.VITE_CASH_REGISTER_ID??'';
function App(){const[barcode,setBarcode]=useState('');const[items,setItems]=useState<Item[]>([]);const[saleId,setSaleId]=useState<string>();const[method,setMethod]=useState<PaymentMethod>(0);const[msg,setMsg]=useState('Готов к продаже');const[busy,setBusy]=useState(false);const total=items.reduce((s,x)=>s+x.qty*x.price,0);
async function ensureSale(){if(saleId)return saleId;if(!STORE||!REGISTER)throw new Error('Не настроены магазин/касса');const s=await api.createSale(STORE,REGISTER);setSaleId(s.id);return s.id}
async function scan(){if(!barcode||busy)return;setBusy(true);try{const s=await ensureSale();const found=await api.lookup(barcode,WAREHOUSE);if(found.stock<=0)throw new Error('Товара нет в наличии');const price=Number(prompt(`Цена: ${found.product.name}`,'0')||0);await api.addBarcode(s,barcode,1,price);setItems(v=>{const old=v.find(x=>x.id===found.product.id);return old?v.map(x=>x.id===old.id?{...x,qty:x.qty+1}:x):[...v,{id:found.product.id,barcode,name:found.product.name,qty:1,price,stock:found.stock}]});setBarcode('');setMsg(`${found.product.name} добавлен`)}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
async function pay(){if(!saleId||total<=0||busy)return;setBusy(true);try{const p=await api.createPayment(saleId,method,total);if(method!==0){const started=await api.startPayment(p.id);if(started.qrPayload)setMsg('QR создан. Ожидание оплаты клиентом…');else setMsg('Ожидание подтверждения банка…')}else setMsg('Платеж наличными создан. Требуется серверное подтверждение.');}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
return <main><header><b>ДАДО</b><span>Продажа · POS</span><aside>{msg}</aside></header><section className="layout"><div className="sale"><div className="scan"><input autoFocus value={barcode} onChange={e=>setBarcode(e.target.value)} onKeyDown={e=>e.key==='Enter'&&scan()} placeholder="Сканируйте штрихкод…"/><button disabled={busy} onClick={scan}>Добавить</button></div><table><thead><tr><th>#</th><th>Товар</th><th>Кол-во</th><th>Остаток</th><th>Цена</th><th>Сумма</th></tr></thead><tbody>{items.map((x,i)=><tr key={x.id}><td>{i+1}</td><td>{x.name}</td><td>{x.qty}</td><td>{x.stock}</td><td>{x.price.toFixed(2)}</td><td>{(x.qty*x.price).toFixed(2)}</td></tr>)}</tbody></table></div><aside className="pay"><h2>К оплате</h2><strong>{total.toFixed(2)} <small>сомони</small></strong><p>Позиций: {items.length}</p><button className="cash" onClick={()=>setMethod(0)}>Наличные {method===0?'✓':''}</button><button className="card" onClick={()=>setMethod(1)}>Карта {method===1?'✓':''}</button><button className="qr" onClick={()=>setMethod(2)}>QR {method===2?'✓':''}</button><button className="bonus" onClick={()=>setMethod(3)}>Бонусы {method===3?'✓':''}</button><hr/><button disabled={busy||!items.length} className="finish" onClick={pay}>Оплатить</button></aside></section></main>}
createRoot(document.getElementById('root')!).render(<App/>);
