FROM mcr.microsoft.com/dotnet/sdk:8.0
WORKDIR /src
COPY . .
RUN dotnet restore src/DadoRetail.Api/DadoRetail.Api.csproj
RUN dotnet tool install --global dotnet-ef --version 8.0.8
ENV PATH="${PATH}:/root/.dotnet/tools"
ENTRYPOINT ["dotnet","ef","database","update","--project","src/DadoRetail.Infrastructure/DadoRetail.Infrastructure.csproj","--startup-project","src/DadoRetail.Api/DadoRetail.Api.csproj"]
